/*
 * gen_delta_tables — emits src/img_delta_tables_data.c with
 * compile-time const SoA tables for the CE Delta engine.
 *
 *   $ make build/gen_delta_tables
 *   $ ./build/gen_delta_tables > src/img_delta_tables_data.c
 *
 * Or simply:
 *
 *   $ make gen-tables
 *
 * This program links against img_delta_compute.o only — it must
 * remain free of dependencies on the runtime tables themselves to
 * avoid a chicken-and-egg link cycle.
 */

#include "img_delta_compute.h"

#include <stdint.h>
#include <stdio.h>

static void emit_header(void) {
    printf(
"/*\n"
" * AUTO-GENERATED by tools/gen_delta_tables.c. Do not edit by hand.\n"
" * Regenerate with:  make -C spatial_ai gen-tables\n"
" *\n"
" * SoA delta lookup tables (SPEC §13.2). Indexed via\n"
" * img_delta_table_idx(mode, tier, scale, sign, tone, depth).\n"
" */\n"
"#include \"img_delta_compute.h\"\n"
"#include <stdint.h>\n"
"\n");
}

static void emit_int16_table(const char* name, const int16_t* v, size_t n) {
    printf("const int16_t %s[IMG_DELTA_TABLE_N] = {\n", name);
    for (size_t i = 0; i < n; i++) {
        if ((i % 12) == 0) printf("    ");
        printf("%6d,", (int)v[i]);
        if ((i % 12) == 11 || i + 1 == n) printf("\n");
        else                                printf(" ");
    }
    printf("};\n\n");
}

static void emit_uint8_table(const char* name, const uint8_t* v, size_t n) {
    printf("const uint8_t %s[IMG_DELTA_TABLE_N] = {\n", name);
    for (size_t i = 0; i < n; i++) {
        if ((i % 16) == 0) printf("    ");
        printf("0x%02X,", (unsigned)v[i]);
        if ((i % 16) == 15 || i + 1 == n) printf("\n");
        else                                printf(" ");
    }
    printf("};\n\n");
}

static void emit_step_table_dir(void) {
    printf("const uint8_t g_direction_step[IMG_FLOW_BUCKETS][IMG_SIGN_MAX] = {\n");
    for (uint8_t d = 0; d < IMG_FLOW_BUCKETS; d++) {
        printf("    { ");
        for (uint8_t s = 0; s < IMG_SIGN_MAX; s++) {
            printf("%u%s", (unsigned)img_delta_compute_direction_step(d, s),
                   (s + 1 < IMG_SIGN_MAX) ? ", " : "");
        }
        printf(" },\n");
    }
    printf("};\n\n");
}

static void emit_step_table_depth(void) {
    printf("const uint8_t g_depth_step[IMG_DEPTH_BUCKETS][IMG_SIGN_MAX] = {\n");
    for (uint8_t d = 0; d < IMG_DEPTH_BUCKETS; d++) {
        printf("    { ");
        for (uint8_t s = 0; s < IMG_SIGN_MAX; s++) {
            printf("%u%s", (unsigned)img_delta_compute_depth_step(d, s),
                   (s + 1 < IMG_SIGN_MAX) ? ", " : "");
        }
        printf(" },\n");
    }
    printf("};\n\n");
}

int main(void) {
    static int16_t core_tbl    [IMG_DELTA_TABLE_N];
    static int16_t link_tbl    [IMG_DELTA_TABLE_N];
    static int16_t delta_tbl   [IMG_DELTA_TABLE_N];
    static int16_t priority_tbl[IMG_DELTA_TABLE_N];
    static uint8_t pattern_tbl [IMG_DELTA_TABLE_N];

    for (uint8_t mode = 0; mode < IMG_MODE_MAX; mode++)
    for (uint8_t tier = 0; tier < IMG_TIER_MAX; tier++)
    for (uint8_t scale = 0; scale < IMG_SCALE_MAX; scale++)
    for (uint8_t sign = 0; sign < IMG_SIGN_MAX; sign++)
    for (uint8_t tone = 0; tone < IMG_TONE_BUCKETS; tone++)
    for (uint8_t depth = 0; depth < IMG_DEPTH_BUCKETS; depth++) {
        size_t i = img_delta_table_idx(mode, tier, scale, sign, tone, depth);
        img_delta_compute_entry(mode, tier, scale, sign, tone, depth,
                                &core_tbl[i], &link_tbl[i], &delta_tbl[i],
                                &priority_tbl[i], &pattern_tbl[i]);
    }

    emit_header();
    emit_int16_table("g_core_table",     core_tbl,     IMG_DELTA_TABLE_N);
    emit_int16_table("g_link_table",     link_tbl,     IMG_DELTA_TABLE_N);
    emit_int16_table("g_delta_table",    delta_tbl,    IMG_DELTA_TABLE_N);
    emit_int16_table("g_priority_table", priority_tbl, IMG_DELTA_TABLE_N);
    emit_uint8_table("g_pattern_table",  pattern_tbl,  IMG_DELTA_TABLE_N);
    emit_step_table_dir();
    emit_step_table_depth();

    return 0;
}
